### ISSUE TITLE
Team Setup and Repo Creation

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/DSCI-532_2024_12_bigmac#1]
What to do: Form your team and create a GitHub repository under the UBC-MDS organization following the specific naming convention provided. This is your project’s development environment where all your work will be stored and tracked.
Why it matters: Setting up a GitHub repository ensures that all team members can collaborate effectively, share code, and track changes. The naming convention helps in easily identifying your project among others.

**Comment by atabak-alishiri** [comment]
- repo created and renamed to bigmac
- main branch protection added
