### ISSUE TITLE
Teamwork Contract Drafting

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/DSCI-532_2024_12_bigmac#4]
What to do: Draft a teamwork contract that formalizes how your team will work together. Include aspects such as communication norms, work distribution, and conflict resolution.
Why it matters: A teamwork contract helps prevent misunderstandings and conflicts by setting clear expectations. It ensures that all team members are on the same page regarding how they will collaborate throughout the project.

**Comment by atabak-alishiri** [comment]
The teamwork contract is ready based on what we discussed in the lab and the final markdown file is posted on Slack.
