### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_12_bigmac#57]
Major:
- [x] #58
- [x] #59
- [x] #60
    - [x] #61

Minor:
- [x] #62
- [x] #63
- [x] #64
- [x] #65
    - [x] #66
- [x] #67
- [x] #68

**Comment by beth-ouyang** [comment]
Checked the tasks that have been done.

**Comment by atabak-alishiri** [comment]
Except the #61 which is the challenging part, everything else from Joel's feedback is done now.
