### ISSUE TITLE
Feedback from Salva Umar

### ISSUE THREAD

**Issue by salva-u** [UBC-MDS/DSCI-532_2024_12_bigmac#70]
Love the unique idea and the execution of your team's dash app. It looks great. The short description at the beginning of the dashboard is excellent and helps provide relevant context for the users. Adding adjustment for inflation is a great touch.

Some points for consideration:
Stylistic - Filters/Slicers Pane: Perhaps it would be nice to have a different color or some form of highlighting behind the filters pane to separate them from the charts in the dashboard.

Stylistic - Chart like the buying power over time chart: The text "buying power over time in X country" sometimes gets cut off. Maybe try using some form of text wrapping to prevent that.

Information display choice - Hourly Wage between the X to Y years: It would be interesting to see how the average Big Mac price relates by countries too. Maybe overlaying both on the same chart could be considered.

Information display - Map: Love that the tooltip shows the dollar price as well as the Big Macs per hour. Instead of showing only the global "Big Macs per hour", it would be nice to see the minimum wage there too.

Calculation/Information display choice - Big Mac price vs. hourly wage chart: Show the percentage difference between minimum wage and Big Mac price in the chart, as the percentage difference can provide a clear indicator of whether Big Mac prices are becoming more or less affordable relative to minimum wage to introduce some metrics for the economists , maybe.

Overall had fun reviewing your guy's dashboard!

**Comment by arturoboquin** [comment]
- [x] UI Enhancement - Filters/Slicers Pane:
    - Task: Update the styling of the filters/slicers pane by adding a distinct background color or some form of highlighting to visually separate it from the dashboard charts.
    - Objective: Improve visual separation and enhance user focus on different sections of the dashboard.

**Comment by arturoboquin** [comment]
- [x] UI Fix - Chart Text Display:
    - Task: Implement text wrapping for the chart titles, especially for "buying power over time in X country" to prevent the text from being cut off.
    - Objective: Ensure all chart titles are fully visible and readable, enhancing user understanding and interaction.

**Comment by arturoboquin** [comment]
- [ ] Feature Addition - Hourly Wage and Big Mac Price Chart:
    - Task: Modify the "Hourly Wage between X to Y years" chart to include a comparison of average Big Mac prices by countries, potentially overlaying this data on the same chart.
    - Objective: Provide a richer data comparison to users, allowing for better insights into global economic conditions.

**Comment by arturoboquin** [comment]
- [ ] Enhancement - Map Tooltip Information:
    - Task: Update the map tooltips to show both the dollar price and the number of Big Macs per hour alongside the minimum wage information.
    - Objective: Provide a more comprehensive economic snapshot at the country level, enhancing the informational value of the map tooltips.

**Comment by arturoboquin** [comment]
- [ ] New Metric Implementation - Big Mac Affordability:
    - Task: Add a new metric to the "Big Mac price vs. hourly wage" chart showing the percentage difference between minimum wage and Big Mac price.
    - Objective: Offer an immediate visual indicator of affordability trends, providing valuable insights for economic analysis.
