### ISSUE TITLE
Feedback from Michelle Hunn

### ISSUE THREAD

**Issue by mishelly-h** [UBC-MDS/DSCI-532_2024_12_bigmac#72]
I really like your Dashboard! You manage to communicate an abstract concept in an easy way. I think the 'Big Macs per hour' is a cool metric that makes the big mac index understandable. Following some ideas that I had while going through your dashboard: 

- Plot reactivity: You have four filter at the top. However, when I changed the input values, not all of the visualizations below updated. I am not sure if this is a bug or if this is intentional. If this is a bug: before your next deployment, make sure that all the visualizations are connected to the filters. If this is intentional: change the position of the filters / use styling to clearly show to the user what filters affect what graph. 
- Target Audience: You mention 'Economists, Policy Makers, Financial Analysts, and the General Public interested in Global Economic Trends' as your target audience. I would assume that an Economist and someone from the general public interested in global economic trends have very different levels of understandings of economic concepts and terms. By trying to make a dashboard suitable for a too wide target audience, you increase the risk of creating a dashboard that fits no one. Therefore, I recommend that you narrow down the target audience. I think your dashboard does a very good job at making these concepts easy to digest with no / little prior knowledge. So, I would recommend focusing on the general public or educational purposes as opposed to specialists in the field. 
- Align plots: the plots that are in the same 'row' do not seem to be aligned. Aligning them would make the dashboard look cleaner. 
- Styling: Use cards to put the plots on. This could increase the visual appeal of the dashboard.  

Overall, I think you have picked an interesting topic that is highly relevant. With your dashboard you break down an abstract concept and make it accessible to the general public. I had fun exploring your dashboard. Good job!

**Comment by arturoboquin** [comment]
- [ ] Bug Fix/Feature Adjustment - Filter Reactivity:
    - Task: Verify and ensure that all visualizations respond to changes in the filter settings. If the current behavior is intentional, adjust the UI to make it clear which filters affect which visualizations, possibly by repositioning filters or using distinct styling.
    - Objective: Ensure consistent and intuitive interaction with filters, enhancing user experience and avoiding confusion.

**Comment by arturoboquin** [comment]
- [ ] Strategy Adjustment - Target Audience Specification:
    - Task: Reevaluate and potentially narrow the target audience of the dashboard. Consider focusing primarily on the general public or educational sectors, given the dashboard's strength in simplifying complex economic concepts.
    - Objective: Tailor content and complexity to better meet the needs and understanding levels of a more specific audience, improving engagement and effectiveness.

**Comment by arturoboquin** [comment]
- [ ] UI Enhancement - Alignment of Plots:
    - Task: Adjust the alignment of plots within the same row across the dashboard to ensure visual consistency and neatness.
    - Objective: Improve the aesthetic appeal and user navigation of the dashboard.

**Comment by arturoboquin** [comment]
- [ ] Styling Enhancement - Use of Cards for Plots:
    - Task: Implement a card-based layout for plots to enhance visual appeal and organize information more effectively.
    - Objective: Create a more visually appealing and structured presentation of data within the dashboard.
