### ISSUE TITLE
Feedback from Runtian Rachel Li

### ISSUE THREAD

**Issue by Rachel0619** [UBC-MDS/DSCI-532_2024_12_bigmac#78]
Overall, the bigmac dashboard is thoughtfully designed and well-executed. It would be an invaluable tool for the users interested in analyzing the inflation rates and in turn its impacts on buying power of different countries over time. I really like the feature that adjusts hourly wages according to inflation, offering a realistic view of wage trends which may be different from the misleading message that the politicians trying to convey. From my viewpoint, there are specific aspects that could be enhanced:
- About the layout: as of the version I am doing peer review on, you might want to move the trend line plot up and also consolidate the input widgets together on top or on the left. A possible layout would be having the input widgets on the left bar, and having a 2 * 2 layout on the right, which would be more visually appealing and user-friendly. The trendline plot could be more compact (you can squeeze it to make it less wide) without losing its effectiveness, as the emphasis is on relative trends rather than details. One of the big advantage of this adjustments would be the users won't need to scroll down the dashboard anymore.
- You might want to rotate the x and y axis for the bar chart. Displaying country names horizontally would help prevent overcrowding and make the data easier to read at a glance.
- You might want to add a footer with the contributor's GitHub username and the dashboard's last update time.
- The  instructional  gif in the README.md file is kind of blurred. If time permits, creating a clearer or higher-resolution GIF would significantly improve the initial user experience.

**Comment by arturoboquin** [comment]
- [ ] Layout Redesign:
    - Task: Revise the dashboard layout to move the trend line plot to a more prominent position and organize input widgets more effectively. Consider placing input widgets on the left sidebar and arranging main content in a 2x2 layout on the right.
    - Objective: Improve visual appeal and user-friendliness by minimizing the need for scrolling and enhancing overall navigability.

**Comment by arturoboquin** [comment]
- [ ] Visualization Adjustment - Trend Line Plot:
    - Task: Modify the trend line plot to make it more compact by reducing its width, ensuring that it still effectively displays relative trends.
    - Objective: Optimize space usage without losing the plot's effectiveness, focusing on relative trends rather than granular details.

**Comment by arturoboquin** [comment]
- [ ] Visualization Adjustment - Bar Chart Orientation:
    - Task: Rotate the x and y axes of the bar chart to display country names horizontally, aiming to alleviate overcrowding and enhance readability.
    - Objective: Make the bar chart data easier to read at a glance, improving data accessibility and comprehension.

**Comment by arturoboquin** [comment]
- [ ] Documentation Improvement - README.md GIF:
    - Task: Update the instructional GIF in the README.md file to be clearer or higher resolution, to better guide new users in using the dashboard.
    - Objective: Enhance initial user experience by providing clear and effective visual instructions.
