### ISSUE TITLE
Feedback from Marco Polo

### ISSUE THREAD

**Issue by Marcony1** [UBC-MDS/DSCI-532_2024_12_bigmac#79]
Hi guys, I found your dashboard to be very interesting! I would have really loved to see information from every country (this is not a correction; it is just a personal comment). I do think it was very clever to combine the Big Mac Index with the minimum wage of every country to estimate purchasing power. However, for the general public inflation adjustment might be unnecessary as the index that you developed already tells them how many Big Macs, they can buy in one hour (maybe you could show how many hamburgers could be bought in a day/8 hours).
Having said the above, here is my feedback: 

•	Regarding the colour fill of the map, I understand that the number of Big Macs is expressed as a continuous value (example: 2.4554654). Although the map let’s the user easily compare which country has a darker “colour”, I think that it may be better if you used a color scale with a countable number of levels (i.e. creating intervals like 0-1, 1-2, 2-3, 3-4, or as many as you find appropriate). And give each interval a different shade of colour either the ones that you are using, or a single colour (i.e. white, light blue, blue, dark blue…). Some information (decimals of a Big Mac) may be lost, but the user would also be able to visually identify which countries belong to the same interval, meaning that they would have a similar purchasing power.

•	Now, focusing on the colour scheme of the map, some countries are small, and it is hard to tell whether they are part of the study case or not. For example, Costa Rica and Israel almost go unnoticed. Maybe highlighting the contour of the countries that are not currently selected in black would help them be more visible.

•	The chart at the bottom of the app mentions “wage” only. To be consistent with the bar chart, I believe it would be a good idea to specify we are looking at an “hourly” wage as well. In some countries, minimum wage is understood as minimum “daily” wage. Since this chart plots wages in the local currency of the selected country, some users may get confused if this is not specified.

•	Since the radio buttons and the graph at the bottom of the app are only visible if you scroll down, maybe it would be a good idea to have multiple pages. You could keep the slider and the dropdown at the top of the app, and then put the next 3 graphs in one page, while the radio buttons and the bottom graph in a second page.

•	I know this doesn’t have to do with the dashboard itself, but I had problems when trying to run the app. I had to install dash_vega_components and geopandas.

```bash
(bigmac_12) Marcony1@MSI ~/OneDrive - Fundacion Universidad de las Americas Puebla/Documents/MDS/Block 6/DSCI 532/DSCI-532_2024_12_bigmac (main)
$ python -m src.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Marcony1\OneDrive - Fundacion Universidad de las Americas Puebla\Documents\MDS\Block 6\DSCI 532\DSCI-532_2024_12_bigmac\src\app.py", line 4, in <module>
    import dash_vega_components as dvc
ModuleNotFoundError: No module named 'dash_vega_components'
```

```bash
(bigmac_12) Marcony1@MSI ~/OneDrive - Fundacion Universidad de las Americas Puebla/Documents/MDS/Block 6/DSCI 532/DSCI-532_2024_12_bigmac (main)
$ python -m src.app
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Marcony1\OneDrive - Fundacion Universidad de las Americas Puebla\Documents\MDS\Block 6\DSCI 532\DSCI-532_2024_12_bigmac\src\app.py", line 13, in <module>
    import geopandas as gpd
ModuleNotFoundError: No module named 'geopandas'
```

Overall, the dashboard looks great. It just needs some polishing, but it really makes you want to know more and explore. Cheers!

**Comment by arturoboquin** [comment]
- [ ] Data Visualization - Map Color Scale:
    - Task: Redesign the color fill of the map by using a color scale with defined intervals (e.g., 0-1, 1-2, 2-3, 3-4 Big Macs) instead of a continuous scale, to simplify visual comparison and enhance user understanding.
    - Objective: Enhance user ability to visually categorize countries with similar purchasing powers, while making the map easier to interpret.

**Comment by arturoboquin** [comment]
- [ ] UI Enhancement - Map Visibility:
    - Task: Highlight the contours of smaller countries, like Costa Rica and Israel, to make them more visible on the map, regardless of whether they are currently selected.
    - Objective: Ensure that all countries, regardless of size, are easily identifiable on the map.

**Comment by arturoboquin** [comment]
- [ ] Consistency Improvement - Wage Description:
    - Task: Specify "hourly" before "wage" in all relevant charts to clarify that the wages are hourly, avoiding confusion with daily or monthly wages.
    - Objective: Provide clear and consistent information to accommodate global users with different understandings of wage contexts.

**Comment by arturoboquin** [comment]
- [ ] UX Design - App Layout:
    - Task: Consider redesigning the dashboard layout to include multiple pages or sections, placing some visualizations on separate navigable pages to reduce the need for scrolling.
    - Objective: Improve navigation and user experience by organizing content more effectively and making important controls readily accessible.

**Comment by arturoboquin** [comment]
- [ ] Technical Issue - Dependency Management:
    - Task: Ensure all necessary libraries, like dash_vega_components and geopandas, are included in the project’s installation instructions or automatically handled via a setup script or dependency file.
    - Objective: Facilitate smooth setup and operation of the dashboard by resolving dependency issues and providing clear setup documentation.
