### ISSUE TITLE
- [ ] UI Enhancement - Filters/Slicers Pane:

### ISSUE THREAD

**Issue by arturoboquin** [UBC-MDS/DSCI-532_2024_12_bigmac#87]
- [x] UI Enhancement - Filters/Slicers Pane:
    - Task: Update the styling of the filters/slicers pane by adding a distinct background color or some form of highlighting to visually separate it from the dashboard charts.
    - Objective: Improve visual separation and enhance user focus on different sections of the dashboard.

_Originally posted by @arturoboquin in https://github.com/UBC-MDS/DSCI-532_2024_12_bigmac/issues/70#issuecomment-2059954811_

**Comment by atabak-alishiri** [comment]
This issue has been addressed during the update on milestone 3. Check this release ([0.3.0](https://github.com/UBC-MDS/DSCI-532_2024_12_bigmac/releases/tag/0.3.0)).
