### ISSUE TITLE
Technical Issue - Dependency Management:

### ISSUE THREAD

**Issue by arturoboquin** [UBC-MDS/DSCI-532_2024_12_bigmac#99]
- [ ] Technical Issue - Dependency Management:
    - Task: Ensure all necessary libraries, like dash_vega_components and geopandas, are included in the project’s installation instructions or automatically handled via a setup script or dependency file.
    - Objective: Facilitate smooth setup and operation of the dashboard by resolving dependency issues and providing clear setup documentation.

_Originally posted by @arturoboquin in https://github.com/UBC-MDS/DSCI-532_2024_12_bigmac/issues/79#issuecomment-2060020101_

**Comment by atabak-alishiri** [comment]
The dependency management issue is addressed by including all necessary libraries such as dash_vega_components and geopandas in the project’s installation instructions and automatically handling them via a setup script or dependency file. This ensures smooth setup and operation of the dashboard. Fixed at the end of milestone three. Check this release ([0.3.0](https://github.com/UBC-MDS/DSCI-532_2024_12_bigmac/releases/tag/0.3.0)).
